using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using A2lEditor.Core.Model;
using ClosedXML.Excel;

namespace A2lEditor.Core.Skeleton;

/// <summary>
/// 从 Excel 生成 A2L 骨架文档。
/// 默认列映射：
///   A=Name, B=LongIdentifier, C=BlockType (MEASUREMENT/CHARACTERISTIC),
///   D=DataType, E=CompuMethod, F=LowerLimit, G=UpperLimit,
///   H=EcuAddressHex, I=Resolution, J=Accuracy
/// 首行为 header（自动跳过）。
/// </summary>
public sealed class A2lSkeletonService : IA2lSkeletonService
{
    public A2lDocument GenerateFromExcel(string excelPath, SkeletonGenerateOptions? options = null)
    {
        if (string.IsNullOrEmpty(excelPath))
            throw new ArgumentException("Excel path must not be empty.", nameof(excelPath));

        var opts = options ?? new SkeletonGenerateOptions();

        using var workbook = new XLWorkbook(excelPath);

        IXLWorksheet ws;
        if (opts.SheetName is not null)
        {
            if (!workbook.Worksheets.Any(w => w.Name == opts.SheetName))
                throw new ArgumentException(
                    $"Sheet '{opts.SheetName}' not found in '{excelPath}'. Available sheets: " +
                    string.Join(", ", workbook.Worksheets.Select(w => $"'{w.Name}'")));
            ws = workbook.Worksheet(opts.SheetName);
        }
        else
        {
            ws = workbook.Worksheet(1);
        }

        var rows = ws.RowsUsed().ToList();
        if (rows.Count <= 1)  // 只有 header 或空
        {
            return EmptyDocument(opts);
        }

        var measurements = new List<A2lMeasurement>();
        var characteristics = new List<A2lCharacteristic>();
        var compuMethodNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var row in rows.Skip(1))  // 跳过 header
        {
            var name = GetCellString(row, 1);
            if (string.IsNullOrEmpty(name)) continue;

            var longId = GetCellString(row, 2);
            var blockType = GetCellString(row, 3);
            var dataTypeStr = GetCellString(row, 4);
            var compuMethod = GetCellString(row, 5);
            var lower = GetCellString(row, 6, "0");
            var upper = GetCellString(row, 7, "255");
            var ecuAddrStr = GetCellString(row, 8, "0");
            var resolution = GetCellString(row, 9, "0");
            var accuracy = GetCellString(row, 10, "0");

            var dataType = ParseDataType(dataTypeStr);
            var ecuAddress = ParseHexAddress(ecuAddrStr);

            if (!string.IsNullOrEmpty(compuMethod))
                compuMethodNames.Add(compuMethod);

            if (string.Equals(blockType, "CHARACTERISTIC", StringComparison.OrdinalIgnoreCase))
            {
                // 用 D 列 DataType 选择 RECORD_LAYOUT 名称
                var recordLayout = string.IsNullOrEmpty(dataTypeStr)
                    ? "Scalar_UBYTE"
                    : "Scalar_" + dataTypeStr.ToUpperInvariant();
                characteristics.Add(new A2lCharacteristic(
                    name, longId, "VALUE", recordLayout, ecuAddress,
                    lower, upper, null, null, new LineRange(0, 0)));
            }
            else
            {
                measurements.Add(new A2lMeasurement(
                    name, longId, dataType, compuMethod,
                    resolution, accuracy, lower, upper,
                    ecuAddress, new LineRange(0, 0)));
            }
        }

        // 自动生成 COMPU_METHOD 存根
        var compuMethods = compuMethodNames
            .Where(n => !string.IsNullOrEmpty(n))
            .Select(name => new A2lCompuMethod(
                name, $"{name}", "LINEAR", "%.2", "",
                1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                new LineRange(0, 0)))
            .ToList();

        // 自动生成 RECORD_LAYOUT
        var recordLayouts = BuildRecordLayouts(measurements, characteristics);

        var module = new A2lModule(
            opts.ModuleName, opts.ModuleComment,
            measurements, characteristics,
            Array.Empty<A2lAxisPts>(),
            compuMethods, recordLayouts,
            Array.Empty<A2lGroup>(),
            null,  // ModPar
            Array.Empty<A2lAxisDescr>(),
            Array.Empty<A2lUserRights>(),
            Array.Empty<A2lVersionInfo>(),
            Array.Empty<A2lAxisPtsX>(),
            new LineRange(0, 0));

        return new A2lDocument(
            A2lVersion.V1_31,
            "SkeletonProject",
            "Generated by a2l-editor skeleton generate",
            "Generated from Excel import",
            null,  // ModCommon
            new[] { module },
            "",   // RawText → semantic emit
            0);
    }

    // ====================================================================
    // 辅助
    // ====================================================================

    private static string GetCellString(IXLRow row, int col, string defaultValue = "")
    {
        var cell = row.Cell(col);
        if (cell.IsEmpty()) return defaultValue;
        var val = cell.GetString();
        return string.IsNullOrWhiteSpace(val) ? defaultValue : val.Trim();
    }

    private static A2lDataType ParseDataType(string s)
    {
        if (string.IsNullOrEmpty(s)) return A2lDataType.UBYTE;
        return s.Trim().ToUpperInvariant() switch
        {
            "UBYTE" => A2lDataType.UBYTE,
            "SBYTE" => A2lDataType.SBYTE,
            "UWORD" => A2lDataType.UWORD,
            "SWORD" => A2lDataType.SWORD,
            "ULONG" => A2lDataType.ULONG,
            "SLONG" => A2lDataType.SLONG,
            "FLOAT32_IEEE" => A2lDataType.FLOAT32_IEEE,
            "FLOAT64_IEEE" => A2lDataType.FLOAT64_IEEE,
            _ => A2lDataType.UBYTE,
        };
    }

    private static ulong ParseHexAddress(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0;
        var clean = s.Trim().TrimStart('0', 'x', 'X');
        if (string.IsNullOrEmpty(clean))
            return 0; // "0x0" or "0"
        if (!ulong.TryParse(clean, NumberStyles.HexNumber,
                CultureInfo.InvariantCulture, out var addr))
            throw new FormatException($"Invalid hex address in Excel: '{s}' — expected 0x-prefixed hex.");
        return addr;
    }

    private static A2lDocument EmptyDocument(SkeletonGenerateOptions opts)
    {
        var module = new A2lModule(opts.ModuleName, opts.ModuleComment,
            Array.Empty<A2lMeasurement>(), Array.Empty<A2lCharacteristic>(),
            Array.Empty<A2lAxisPts>(), Array.Empty<A2lCompuMethod>(),
            Array.Empty<A2lRecordLayout>(), Array.Empty<A2lGroup>(), null,
            Array.Empty<A2lAxisDescr>(), Array.Empty<A2lUserRights>(),
            Array.Empty<A2lVersionInfo>(), Array.Empty<A2lAxisPtsX>(),
            new LineRange(0, 0));

        return new A2lDocument(A2lVersion.V1_31, "SkeletonProject",
            "Generated by a2l-editor skeleton generate", "", null,
            new[] { module }, "", 0);
    }

    /// <summary>根据 measurements/characteristics 中的数据类型构建 RECORD_LAYOUT 列表。</summary>
    private static List<A2lRecordLayout> BuildRecordLayouts(
        List<A2lMeasurement> measurements, List<A2lCharacteristic> characteristics)
    {
        var dts = new HashSet<string>(StringComparer.Ordinal);
        foreach (var m in measurements) dts.Add(m.DataType.ToString());
        foreach (var c in characteristics) dts.Add("UBYTE");  // CHARACTERISTIC 默认 Scalar_UBYTE

        var layouts = new List<A2lRecordLayout>();
        foreach (var dt in dts.OrderBy(x => x))
        {
            layouts.Add(new A2lRecordLayout(
                $"Scalar_{dt}",
                new[]
                {
                    new RecordLayoutEntry("FNC_VALUES", 1, dt, "COLUMN_DIR", "DIRECT", null, null),
                },
                new LineRange(0, 0)));
        }
        return layouts;
    }
}
